### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by Crashandburnds** [skoumalcz/arduino-id-guard#1]
Currently Reads 
```
// Only reads ID from EEPROM.
  uint8_t device_id = IdGuard.readId(DEVICE_ID);
```
ReadID() - has no supporting arguments for DEVICE_ID so should read as.
```
// Only reads ID from EEPROM.
  uint8_t device_id = IdGuard.readId();
```

**Comment by gingo** [comment]
@Crashandburnds You are right, `DEVICE_ID` removed from documentation. Thank you for your contribution!
